server {
    listen 80;
    
    root /usr/share/nginx/html;
    index index.html;

    # C'est cette ligne qui fait toute la magie pour React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimisation optionnelle pour garder les assets en cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}